# Site
name: Urdaneta City University
description: A public website of Urdaneta City University
meta_description: "UCU Website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ""
email: 'aljohndeguzman@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: "urdanetacityuniversity"

# Social
social:
  facebook: https://facebook.com/ucuofficial
  twitter: https://twitter.com/ucuofficial
  google_plus: https://plus.google.com/+ucueduphOfficial
  instagram: https://instagram.com/ucuofficial


# Authors
authors:
  ajdeguzman:
    name: Aljohn De Guzman
    display_name: ajdeguzman
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: aljohndeguzman@gmail.com
    web: https://ajdeguzman.github.io
    twitter: https://twitter.com/iamajdeguzman. You are currently previewing Jekyll template demo."
 
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge